name: tutorinhoho
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.1.1
  flutter_auth_buttons: ^0.6.0
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  firebase_core: ^0.4.3+3
  font_awesome_flutter: ^8.0.0
  firebase_database:
  firebase_storage:
  charts_flutter:
  provider:
  flutter_money_formatter:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/guru.jpg
    - assets/image/ABDUL.png
    - assets/image/kabah.jpg
    - assets/image/tuktuk2.png
    - assets/image/google_logo.png
    - assets/image/gambar1.jpg
    - assets/image/bintang.png
    - assets/image/jengjeng.png
    - assets/image/study.png
    - assets/image/super.png
    - assets/image/math.png
    - assets/image/fis.png
    - assets/image/kim.png
    - assets/image/ekonomi.png
    - assets/image/geo.png
    - assets/image/history.png
    - assets/image/socio.png
    - assets/image/bio.png
    - assets/image/math.jpg
    - assets/image/phy.jpg
    - assets/image/economic.jpg
    - assets/image/geo.jpg
    - assets/image/history.jpg
    - assets/image/kim.jpg
    - assets/image/socio.jpg
    - assets/image/bio.jpg
    - assets/image/belajar.png
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Worksans
       fonts:
         - asset: assets/fonts/Worksans-Regular.ttf
         - asset: assets/fonts/Worksans-Medium.ttf
           weight: 500
         - asset: assets/fonts/Worksans-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Worksans-Bold.ttf
           weight: 700


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
